name: Testing stuff

on:
  push:
    branches:
      - feature

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: is not skip commit messages
        env:
          NOT_SKIP_COMMIT_MESSAGES: ${{ !contains(join(github.event.commits.*.message, ','), '#skip') }}
        run: echo "$NOT_SKIP_COMMIT_MESSAGES"
      - name: is skip commit messages
        env:
          SKIP_COMMIT_MESSAGES: ${{ contains(join(github.event.commits.*.message, ','), '#skip') }}
        run: echo "$SKIP_COMMIT_MESSAGES"